global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'openmeteo'
    static_configs:
      - targets: ['openmeteo-exporter:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
